# @format

name: "integration-case"
services:
  single-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: integration-case-single-server
    networks:
      - integration-case

  redis:
    image: redis:latest
    container_name: integration-case-redis
    networks:
      - integration-case

  distributed-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: integration-case-distributed-server
    environment:
      - isDistributed=true
    networks:
      - integration-case
    depends_on:
      - redis

networks:
  integration-case:
    driver: bridge
    name: integration-case
